import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { initializeDatabase } from "./config/database.js";
import userRoutes from "./routes/userRoutes.js";
dotenv.config();
const app = express();
const PORT = process.env.PORT || 5000;
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.get("/api/health", (req, res) => { res.json({ status: "OK", message: "Backend server is running" }); });
app.get("/", (req, res) => { res.json({ message: "Welcome to the System Development Backend API" }); });
app.use("/api/users", userRoutes);
app.use((req, res) => { res.status(404).json({ error: "Route not found" }); });
app.use((err, req, res, next) => { console.error(err.stack); res.status(500).json({ error: "Internal server error" }); });
const startServer = async () => { try { await initializeDatabase(); app.listen(PORT, () => { console.log(`✓ Server is running on http://localhost:${PORT}`); }); } catch (error) { console.error("❌ Failed to start server:", error.message); process.exit(1); } };
startServer();
